name: docs

on:
  # push到main分支时触发
  push:
    branches: [main]

jobs:
  docs:
    if: contains(github.event.head_commit.message, '[ci]')
    runs-on: ubuntu-latest
    steps:
      - name: 分支拉取
        uses: actions/checkout@v4

      # 安装 bun
      - name: 安装bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 缓存 bun 依赖
      - name: 缓存依赖
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # 安装依赖
      - name: 安装依赖
        run: bun install

      # 构建Vue组件包
      - name: 构建Vue组件
        run: bun run --cwd packages/vue build

      # 构建文档
      - name: 构建文档
        run: bun run --cwd playground build:doc

      # 部署
      - name: 部署到github page中
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: playground/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
